# Theme settings
doks:
    baseurl:
    color_theme: yellow # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Nandita Guerin
            image:
        nav:
            - item_name: Les cours
              item_url: /cours
            - item_name: Actualités
              item_url: /actualites
            - item_name: Expérience
              item_url: /experience
            - item_name: Contact
              item_url: /contact
    footer:
        content:
            logo:
                text: Nandita Guerin
                image:
            copyright: © Nandita Guerin
        social_list:
            - network_name: github
              profile_url: https://github.com/nanditaguerin/nanditaguerin.github.io

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
